name: wemsave
description: WemSave - Скачивание видео из ВК, YouTube и Pinterest | by Wemiann
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # Функционал
  http: ^1.2.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  dio: ^5.4.3
  clipboard: ^0.1.3
  
  # Сохранение в галерею (замена gallery_saver)
  image_gallery_saver: ^2.0.3
  
  # Ссылки и шаринг
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  
  # Уведомления
  flutter_local_notifications: ^17.2.3
  
  # Видео плеер
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
